# Generated by Django 5.1.4 on 2025-01-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_business_alter_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='business',
            name='verification_token',
        ),
    ]
