# Generated by Django 5.1.4 on 2025-01-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_create_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
    ]
