# Generated by Django 5.1.4 on 2025-01-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_acquired', models.PositiveSmallIntegerField()),
                ('asset_types', models.CharField(choices=[('Current', 'current'), ('Fixed', 'fixed'), ('Intangible', 'intangible'), ('Investment', 'investment'), ('Other', 'other'), ('Real Estate', 'real estate'), ('Land', 'land')], max_length=20)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('useful_life', models.IntegerField()),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valuation_method', models.CharField(choices=[('Straight-Line', 'straight line'), ('Declining-Balance', 'declining-balance'), ('Units-of-Production', 'units-of-production'), ('Sum-of-the-Years-Digits', 'sum-of-the-years-digits'), ('Double-Declining-Balance', 'double-declining-balance'), ('Appreciation', 'appreciation')], max_length=30)),
                ('is_appreciating', models.BooleanField(default=False)),
                ('monthly_depreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_depreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_appreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_appreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=255)),
                ('date_incurred', models.DateField()),
                ('liability_type', models.CharField(choices=[('Current', 'Current'), ('Long-term', 'Long-term'), ('Contingent', 'Contingent'), ('Other', 'Other')], max_length=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('collateral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_collateral', to='finance.collateral')),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.creditor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collateral',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collateral_asset', to='finance.liability'),
        ),
        migrations.AddField(
            model_name='collateral',
            name='liability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_collateral', to='finance.liability'),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='finance.liability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expense_category', models.CharField(choices=[('Rent', 'rent'), ('Utilities', 'utilities'), ('Salaries', 'salaries'), ('Office Supplies', 'office supplies'), ('Travel', 'travel'), ('Marketing', 'marketing'), ('Maintenance', 'maintenance'), ('Miscellaneous', 'miscellaneous')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigeria Naira'), ('GBP', 'British Pound'), ('YEN', 'Yen')], max_length=15)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'expense_category', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source', models.CharField(choices=[('Sales', 'S'), ('Investment', 'I'), ('Loan', 'L'), ('Other', 'O')], max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigeria Naira'), ('GBP', 'British Pound'), ('YEN', 'Yen')], max_length=15)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'source', 'description')},
            },
        ),
    ]
