# Generated by Django 5.1.4 on 2024-12-21 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=11)),
                ('account_name', models.CharField(max_length=15)),
                ('account_type', models.CharField(choices=[('CURRENT Account', 'current account'), ('SAVINGS Account', 'savings account'), ('Corporate Account', 'corporate account'), ('Domiciliary Account', 'domiciliary account'), ('Joint Account', 'joint account'), ('Business Loan Account', 'business loan account')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expense_category', models.CharField(choices=[('Rent', 'rent'), ('Utilities', 'utilities'), ('Salaries', 'salaries'), ('Office Supplies', 'office supplies'), ('Travel', 'travel'), ('Marketing', 'marketing'), ('Maintenance', 'maintenance'), ('Miscellaneous', 'miscellaneous')], max_length=50)),
                ('description', models.TextField()),
                ('currency', models.CharField(choices=[('Rent', 'rent'), ('Utilities', 'utilities'), ('Salaries', 'salaries'), ('Office Supplies', 'office supplies'), ('Travel', 'travel'), ('Marketing', 'marketing'), ('Maintenance', 'maintenance'), ('Miscellaneous', 'miscellaneous')], max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source', models.CharField(choices=[('Sales', 'S'), ('Investment', 'I'), ('Loan', 'L'), ('Other', 'O')], max_length=15)),
                ('description', models.TextField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigeria Naira'), ('GBP', 'British Pound'), ('YEN', 'Yen')], max_length=15)),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('transaction_types', models.CharField(choices=[('INCOME', 'income'), ('EXPENSE', 'expense'), ('TRANSFER', 'transfer'), ('OTHER', 'other')], verbose_name=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigeria Naira'), ('GBP', 'British Pound'), ('YEN', 'Yen')], max_length=15)),
                ('bank_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.bankaccount')),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
