# Generated by Django 5.1.4 on 2025-01-04 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('users', '0010_alter_business_user_alter_user_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expense_category', models.CharField(choices=[('Rent', 'rent'), ('Utilities', 'utilities'), ('Salaries', 'salaries'), ('Office Supplies', 'office supplies'), ('Travel', 'travel'), ('Marketing', 'marketing'), ('Maintenance', 'maintenance'), ('Miscellaneous', 'miscellaneous')], max_length=50)),
                ('description', models.TextField()),
                ('currency', models.CharField(choices=[('Rent', 'rent'), ('Utilities', 'utilities'), ('Salaries', 'salaries'), ('Office Supplies', 'office supplies'), ('Travel', 'travel'), ('Marketing', 'marketing'), ('Maintenance', 'maintenance'), ('Miscellaneous', 'miscellaneous')], max_length=15)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'expense_category', 'description')},
            },
        ),
    ]
