# Generated by Django 5.1.4 on 2025-01-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentschedule',
            name='installment_amount',
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='liability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='finance.liability'),
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remaining_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.paymentschedule')),
            ],
        ),
    ]
