# Generated by Django 5.1.4 on 2024-12-22 23:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user_Id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 22, 23, 27, 54, 987521, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('user', 'date', 'expense_category', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('user', 'date', 'source', 'description')},
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_acquired', models.PositiveSmallIntegerField()),
                ('asset_types', models.CharField(choices=[('Current', 'current'), ('Fixed', 'fixed'), ('Intangible', 'intangible'), ('Investment', 'investment'), ('Other', 'other'), ('Real Estate', 'real estate'), ('Land', 'land')], max_length=20)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('useful_life', models.IntegerField()),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valuation_method', models.CharField(choices=[('Straight-Line', 'straight line'), ('Declining-Balance', 'declining-balance'), ('Appreciation', 'appreciation')], max_length=30)),
                ('is_appreciating', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_issued', models.DateField()),
                ('equity_type', models.CharField(choices=[('Common Stock', 'Common Stock'), ('Preferred Stock', 'Preferred Stock'), ('Retained Earnings', 'Retained Earnings'), ('Other', 'Other')], max_length=50)),
                ('dividend_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('date_incurred', models.DateField()),
                ('liability_type', models.CharField(choices=[('Current', 'Current'), ('Long-term', 'Long-term'), ('Contingent', 'Contingent'), ('Other', 'Other')], max_length=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('collateral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_collateral', to='finance.collateral')),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.creditor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collateral',
            name='liability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liability_collateral', to='finance.liability'),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('liability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='finance.liability')),
            ],
        ),
    ]
