# Generated by Django 5.1.4 on 2025-01-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigeria Naira'), ('GBP', 'British Pound'), ('YEN', 'Yen')], max_length=15),
        ),
    ]
