# Generated by Django 5.1.4 on 2025-01-04 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expense_currency'),
        ('users', '0010_alter_business_user_alter_user_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_acquired', models.PositiveSmallIntegerField()),
                ('asset_types', models.CharField(choices=[('Current', 'current'), ('Fixed', 'fixed'), ('Intangible', 'intangible'), ('Investment', 'investment'), ('Other', 'other'), ('Real Estate', 'real estate'), ('Land', 'land')], max_length=20)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('useful_life', models.IntegerField()),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valuation_method', models.CharField(choices=[('Straight-Line', 'straight line'), ('Declining-Balance', 'declining-balance'), ('Appreciation', 'appreciation')], max_length=30)),
                ('is_appreciating', models.BooleanField(default=False)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
