# Generated by Django 5.1.4 on 2025-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='annual_maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='monthly_appreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='monthly_depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='yearly_appreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='yearly_depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='valuation_method',
            field=models.CharField(choices=[('Straight-Line', 'straight line'), ('Declining-Balance', 'declining-balance'), ('Units-of-Production', 'units-of-production'), ('Sum-of-the-Years-Digits', 'sum-of-the-years-digits'), ('Double-Declining-Balance', 'double-declining-balance'), ('Appreciation', 'appreciation')], max_length=30),
        ),
    ]
