# Generated by Django 5.1.4 on 2025-01-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_accountspayable_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountspayable',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='accountsreceivable',
            name='updated_at',
        ),
    ]
