# Generated by Django 5.1.4 on 2025-01-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_collateral_creditor_liability_collateral_liability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collateral_asset', to='finance.liability'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='liability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_collateral', to='finance.liability'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='liability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='finance.liability'),
        ),
    ]
