# Generated by Django 5.1.4 on 2025-01-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_accountspayable_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinstallment',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
