# Generated by Django 5.1.4 on 2025-01-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymentinstallment_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
