# Generated by Django 6.0.7 on 2026-07-24 01:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_macrodatalog_macrosnapshot_account_assetdisposal_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_deductible', models.BooleanField(default=True, help_text='Whether this expense is tax-deductible')),
                ('macro_correlation', models.CharField(choices=[('NONE', 'No Macro Correlation'), ('FX_USD', 'USD/NGN Exchange Rate'), ('DIESEL', 'Diesel Price Index'), ('INFLATION', 'CPI Inflation Rate'), ('ENERGY', 'Energy Price Index'), ('INTEREST', 'Interest Rate')], default='NONE', help_text='Which macro indicator this expense category correlates with', max_length=20)),
                ('budget_limit_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget cap for this category (optional)', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='users.business')),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Office Rent, DSTV Subscription', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUALLY', 'Semi-Annually'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=15)),
                ('next_due_date', models.DateField(help_text='The next date this expense is due')),
                ('start_date', models.DateField(help_text='When this recurring expense started')),
                ('end_date', models.DateField(blank=True, help_text='When this recurring expense ends (null = indefinite)', null=True)),
                ('auto_escalation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual escalation rate in % (e.g. rent increases 10% yearly)', max_digits=6)),
                ('last_escalation_date', models.DateField(blank=True, null=True)),
                ('payee', models.CharField(blank=True, default='', help_text='Who receives this payment (landlord, utility company, etc.)', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='users.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='finance.expensecategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reminder_type', models.CharField(choices=[('RECURRING_EXPENSE', 'Recurring Expense'), ('LIABILITY_PAYMENT', 'Liability Payment'), ('TAX_FILING', 'Tax Filing'), ('INVOICE_FOLLOWUP', 'Invoice Follow-up'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The financial obligation amount associated with this reminder', max_digits=20)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('materiality_score', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='obligation_amount / monthly_revenue', max_digits=6)),
                ('coverage_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='current_cash / obligation_amount', max_digits=6)),
                ('urgency_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('URGENT', 'Urgent'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('SNOOZED', 'Snoozed'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('escalation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users.business')),
                ('liability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.liability')),
                ('recurring_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.recurringexpense')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-urgency_level'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('ACKNOWLEDGED', 'Acknowledged'), ('SNOOZED', 'Snoozed'), ('ESCALATED', 'Escalated')], max_length=15)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Notification'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.reminder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin_number', models.CharField(blank=True, default='', help_text='Tax Identification Number (TIN)', max_length=50)),
                ('is_vat_registered', models.BooleanField(default=False, help_text='If true, VAT is automatically calculated on sales')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text='Standard Nigerian VAT rate is 7.5%', max_digits=5)),
                ('is_wht_agent', models.BooleanField(default=False, help_text='If true, business must deduct Withholding Tax from suppliers')),
                ('cit_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Corporate Income Tax rate (0% small, 20% medium, 30% large)', max_digits=5)),
                ('fiscal_year_end', models.IntegerField(choices=[(1, 'January 31'), (2, 'February 28/29'), (3, 'March 31'), (4, 'April 30'), (5, 'May 31'), (6, 'June 30'), (7, 'July 31'), (8, 'August 31'), (9, 'September 30'), (10, 'October 31'), (11, 'November 30'), (12, 'December 31')], default=12)),
                ('tax_office', models.CharField(blank=True, default='', help_text='FIRS or State IRS office location', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_config', to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('VAT', 'Value Added Tax (7.5%)'), ('WHT', 'Withholding Tax'), ('PAYE', 'Pay As You Earn'), ('CIT', 'Corporate Income Tax'), ('EDT', 'Education Tax (3%)'), ('OTHER', 'Other Tax')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_liability', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('FILED', 'Filed'), ('PAID', 'Paid')], default='DRAFT', max_length=15)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('firs_receipt_number', models.CharField(blank=True, default='', max_length=100)),
                ('report_data_json', models.JSONField(blank=True, default=dict, help_text='The full calculated breakdown of this return')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to='users.business')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_tax_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('business', 'tax_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='TaxFilingDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('VAT', 'Value Added Tax (7.5%)'), ('WHT', 'Withholding Tax'), ('PAYE', 'Pay As You Earn'), ('CIT', 'Corporate Income Tax'), ('EDT', 'Education Tax (3%)'), ('OTHER', 'Other Tax')], max_length=10)),
                ('period_name', models.CharField(help_text='e.g. March 2026 VAT', max_length=100)),
                ('deadline_date', models.DateField()),
                ('is_filed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_deadlines', to='users.business')),
                ('related_return', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline', to='finance.taxreturn')),
            ],
            options={
                'ordering': ['deadline_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('VAT', 'Value Added Tax (7.5%)'), ('WHT', 'Withholding Tax'), ('PAYE', 'Pay As You Earn'), ('CIT', 'Corporate Income Tax'), ('EDT', 'Education Tax (3%)'), ('OTHER', 'Other Tax')], max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='The amount upon which the tax is calculated', max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('is_remitted', models.BooleanField(default=False, help_text='Whether this specific tax amount has been paid to the authority')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='users.business')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_implications', to='finance.transaction')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
