# Generated by Django 6.0.7 on 2026-07-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_product_invoicelineitem_product'),
        ('finance', '0010_expensecategory_recurringexpense_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('OPEX', 'Operating Expense'), ('STOCK', 'Stock / Goods')], default='OPEX', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases', to='billing.product'),
        ),
    ]
